// Parity test: JS ports vs the Python pipeline, on fixtures generated by
// scripts/make_parity_fixture.py. Run with: node app/web/parity.test.js
//
//   {trial_id}.json           -> per-frame normalize.js parity
//   pipeline_{trial_id}.json  -> full pipeline (dominant + normalize +
//                                carry-forward + left mirror + resample)
//
// This must pass before any UI work.

const fs = require("fs");
const path = require("path");
const assert = require("assert");

const { normalizeFrame } = require("./normalize.js");
const { dominantLabel, buildFeatures, resample } = require("./pipeline.js");

const TOL = 1e-5;
const FIX_DIR = path.join(__dirname, "fixtures");

function maxDiff(got, exp, ctx) {
  assert.strictEqual(got.length, exp.length, `${ctx}: length mismatch`);
  let m = 0;
  for (let j = 0; j < exp.length; j++) {
    const d = Math.abs(got[j] - exp[j]);
    assert.ok(Number.isFinite(d), `${ctx} dim ${j}: non-finite (got ${got[j]}, exp ${exp[j]})`);
    if (d > m) m = d;
  }
  return m;
}

// --- Part A: per-frame normalize parity ---------------------------------
function normalizeParity(files) {
  console.log("normalize.js (per-frame):");
  let globalMax = 0;
  for (const file of files) {
    const fx = JSON.parse(fs.readFileSync(path.join(FIX_DIR, file), "utf8"));
    let fileMax = 0;
    fx.frames.forEach((frame, t) => {
      const got = normalizeFrame([frame.handA, frame.handB], frame.pose);
      fileMax = Math.max(fileMax, maxDiff(got, fx.expected[t], `${file} frame ${t}`));
    });
    globalMax = Math.max(globalMax, fileMax);
    console.log(`  ${file}: ${fx.frames.length} frames, max abs diff ${fileMax.toExponential(3)}`);
  }
  return globalMax;
}

// --- Part B: full-pipeline parity (dominant + mirror + resample) --------
function pipelineParity(files) {
  console.log("pipeline.js (dominant + mirror + resample):");
  let globalMax = 0;
  for (const file of files) {
    const fx = JSON.parse(fs.readFileSync(path.join(FIX_DIR, file), "utf8"));
    const handMaps = fx.frames.map((f) => f.hands);
    const poses = fx.frames.map((f) => f.pose);

    const dominant = dominantLabel(handMaps);
    assert.strictEqual(dominant, fx.dominant, `${file}: dominant ${dominant} != ${fx.dominant}`);

    const arr = buildFeatures(handMaps, poses, dominant);
    const out = resample(arr, fx.target_frames);
    assert.strictEqual(out.length, fx.expected.length, `${file}: frame count mismatch`);

    let fileMax = 0;
    for (let t = 0; t < out.length; t++) {
      fileMax = Math.max(fileMax, maxDiff(out[t], fx.expected[t], `${file} frame ${t}`));
    }
    globalMax = Math.max(globalMax, fileMax);
    console.log(
      `  ${file}: T=${fx.n_frames_segment}->${fx.target_frames}, dominant=${dominant}, ` +
        `max abs diff ${fileMax.toExponential(3)}`
    );
  }
  return globalMax;
}

function run() {
  const all = fs.readdirSync(FIX_DIR).filter((f) => f.endsWith(".json")).sort();
  const pipeFiles = all.filter((f) => f.startsWith("pipeline_"));
  const normFiles = all.filter((f) => !f.startsWith("pipeline_"));
  assert.ok(normFiles.length > 0, "no normalize fixtures found");
  assert.ok(pipeFiles.length > 0, "no pipeline fixtures found");

  const normMax = normalizeParity(normFiles);
  console.log("");
  const pipeMax = pipelineParity(pipeFiles);

  const globalMax = Math.max(normMax, pipeMax);
  console.log(
    `\nparity: ${normFiles.length} normalize + ${pipeFiles.length} pipeline fixtures, ` +
      `max abs diff ${globalMax.toExponential(3)} (tol ${TOL.toExponential(0)})`
  );
  assert.ok(globalMax < TOL, `parity FAILED: ${globalMax} >= ${TOL}`);
  console.log("PARITY OK");
}

run();
